services:
  - type: web
    name: devils-will-rise-bot
    env: docker
    dockerfilePath: ./dockerfile
    plan: starter
    healthCheckPath: /
    autoDeploy: false
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: GROUP_ID
        sync: false
      - key: GROUP_LINK
        sync: false
      - key: PAYMENT_UPI
        sync: false
      - key: SUPPORT_USERNAME
        sync: false
      - key: BOT_USERNAME
        sync: false
      - key: LHOST
        sync: false
      - key: LPORT
        sync: false
      - key: PORT
        value: 10000
